### ISSUE TITLE
Progress Tracking

### ISSUE THREAD

**Issue by matcool** [matcool/cocos2d-x-gd#1]
- [x] enough symbols for gd to open
- [x] add hd and uhd suffixes depending on the texture quality
- [x] debug build breaks :(
  * std::string dtor crash in CCFileUtils::setAndroidPath
- [x] i think dynamic_cast is broken
  * its not
- [ ] touch prio needs to be impld
- [ ] much of ZipUtils

**Comment by altalk23** [comment]
self notes for 4 hours later:
- typeinfo cast is needed
